services:
  llamadle:
    image: justinkozlowski/projects:llamadle
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: llamadle-app
    environment:
      - VIRTUAL_HOST=www.justinkozlowski.me
      - LETSENCRYPT_HOST=www.justinkozlowski.me
      - LETSENCRYPT_EMAIL=contact@justinkozlowski.me
      - VIRTUAL_PATH=/llamadle
    network_mode: bridge
